[platformio]
default_envs = d1_mini

; ── D1 Mini (ESP8266) — bez displeja, bez enkodera ────────
[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino

upload_port = COM7
monitor_port = COM7
monitor_speed = 115200

board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld

build_flags =
    -DDISPLAY_NONE
    -DESP8266

lib_deps =
    https://github.com/me-no-dev/ESPAsyncTCP.git
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.5
